### ISSUE TITLE
Community health files

### ISSUE THREAD

**Issue by hauten** [LLNL/.github#22]
This repo
- [x] Create folder for community health files & move release template into it (PR #19)
- [x] Code of conduct template (PR #20)
- [x] Contributing guidelines template (PR #21)
- [x] Notice template (PR #23)
- [x] Issue template (PR #24)
- [x] PR template (generic, noting that each project is very different in what they prefer) (PR #25)
- [x] Re: license, update README to point to portal resources & examples (more informational than templated)  (PR #26) 
- [x] Review/clean up any files as needed (e.g., consistent formatting) (PR #26) 
- [x] Update links on README as I go (various PRs)
- [x] Create release notes (https://github.com/LLNL/.github/releases/tag/v1.2)

software.llnl.gov
- [x] Update release notes link on FAQ line 103 (https://github.com/LLNL/llnl.github.io/pull/466)
- [x] Add CoC and Contrib links to FAQ (https://github.com/LLNL/llnl.github.io/pull/466)
- [x] Update Notice link on FAQ line 101 (https://github.com/LLNL/llnl.github.io/pull/467)
- [x] Add/clarify link to this repo on Licenses page (https://github.com/LLNL/llnl.github.io/pull/467)
- [x] Create news item to advertise this repo's new offerings (https://github.com/LLNL/llnl.github.io/pull/473)

dev.llnl.gov
- [x] Update /opensource/ page (Bitbucket PR no. 6)

Resources:
- https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/creating-a-default-community-health-file
- https://github.com/18F/.github

**Comment by hauten** [comment]
@IanLee1521 Would you like to review these new pages & provide feedback before I finish the last two tasks in this issue?

**Comment by IanLee1521** [comment]
By which you mean look at https://github.com/LLNL/llnl.github.io/pull/467/files ? That looks great, I'll go ahead and merge that.

**Comment by hauten** [comment]
> By which you mean look at https://github.com/LLNL/llnl.github.io/pull/467/files ? That looks great, I'll go ahead and merge that.

See the new files: https://github.com/LLNL/.github/tree/master/community-health

**Comment by hauten** [comment]
@IanLee1521 friendly reminder... please look at the community health files themselves https://github.com/LLNL/.github/tree/master/community-health
